# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-31 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('penulis', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('BRT', 'Berita'), ('INF', 'Info'), ('JNL', 'Jurnal')], default='BRT', max_length=50)),
                ('timeUpdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
