# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-31 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='kategori',
            field=models.CharField(choices=[('Berita', 'berita'), ('Info', 'info'), ('Jurnal', 'jurnal')], default='BRT', max_length=50),
        ),
    ]
